# Generated by Django 5.0.4 on 2024-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_routine_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15),
        ),
    ]
