# Generated by Django 5.0.4 on 2024-04-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_students', '0004_remove_gymstudent_routines'),
        ('routines', '0006_alter_routine_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='exercises',
        ),
        migrations.AddField(
            model_name='routine',
            name='gym_student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='gym_students.gymstudent'),
        ),
    ]
