# Generated by Django 5.0.4 on 2024-04-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_students', '0004_remove_gymstudent_routines'),
        ('routines', '0007_remove_routine_exercises_routine_gym_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='gym_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='gym_students.gymstudent'),
        ),
    ]
