# Generated by Django 5.0.4 on 2024-04-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0002_alter_routine_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number_of_sets', models.IntegerField(default=4)),
                ('number_of_reps_per_set', models.IntegerField(default=12)),
                ('load', models.IntegerField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='routines.routine')),
            ],
        ),
    ]
