# Generated by Django 5.0.4 on 2024-04-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_routine'),
        ('routines', '0008_alter_routine_gym_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='routine',
        ),
        migrations.AddField(
            model_name='exercise',
            name='routine',
            field=models.ManyToManyField(related_name='exercises', to='routines.routine'),
        ),
    ]
